version: '3'
services:
  docdb:
    # use a mongo image that most closely matches the DocumentDB API
    image: mongo:3.6.20-xenial
    container_name: mongo
    env_file: .docker-env
    networks: ["cve-services"]
    ports: ["27017:27017"]
  cveawg:
    container_name: cveawg
    build:
      context: ../
      dockerfile: docker/Dockerfile.dev
    depends_on: [docdb]
    env_file: .docker-env
    networks: ["cve-services"]
    ports: ["3000:3000"]
    volumes:
      - ../package.json:/app/package.json
      - ../src:/app/src
      - ../test:/app/test
      - ../test-examples:/app/test-examples
      - ../test-utils:/app/test-utils
      - ../.eslintrc.js:/app/.eslintrc.js

networks:
  cve-services:
