on:
  issues:
    types: [labeled] # opened,edited,transferred,
name: Assign draft label when the user story label is assigned
jobs:
  processLabels:
    name: Process Label Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Process Label Action
        uses: hramos/label-actions@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}