name: "Node Integration Tests"

# run this on a pull request for testing
on:
  pull_request:

# use a single job at first
jobs:
  run-integration-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Build and Run Services and Mongo Containers
      run: |
        cp docker/.docker-env.test-example docker/.docker-env
        docker compose --file docker/docker-compose.yml build
        docker compose --file docker/docker-compose.yml up -d
    - name: Sleep
      run: bash -c "while ! docker compose --file docker/docker-compose.yml logs --tail=10 cveawg | grep -q 'Serving on port'; do sleep 1; done"
    - name: Run Tests
      run: docker compose -f docker/docker-compose.yml exec -T cveawg npm run test:integration
      continue-on-error: false