name: "Black Box Testing"

# run this on a pull request for testing
on:
  pull_request:

# use a single job at first
jobs:
  run-functional-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Build and Run Services and Mongo Containers
      run: |
        cp docker/.docker-env.example docker/.docker-env
        docker-compose --file docker/docker-compose.yml build
        docker-compose --file docker/docker-compose.yml up &
    - name: Build Test Container
      run: |
        cd test-http/
        cp docker/.docker-env.example docker/.docker-env
        docker-compose --file docker/docker-compose.yml build
    - name: Run Test Container
      run: |
        cd test-http/
        docker-compose --file docker/docker-compose.yml up &
    - name: Sleep
      run: sleep 30
    - name: Load Data into MongoDb
      run: docker exec cveawg npm run populate:dev y
    - name: Run Black Box Tests
      run: |
        cd test-http/
        docker exec demon pytest src/ > src/testOutput.txt
    - name: Check Tests Output
      run: docker exec -it demon /bin/bash src/parse_tests_output.sh | (read foo; echo "##[set-output name=result;]$(echo $foo)")
      id: tests_result
    - name: Evaluate Tests Output
      if: ${{ steps.tests_result.outputs.result == 'Tests failed' }}
      run: exit 1
    
    

